name: Minerai-Mithril
version: '${project.version}'
main: com.github.unldenis.premiumsponge.PremiumSponge
depend: [ WorldGuard ]
authors: [ unldenis ]
commands:
  removesponges:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
