name: PremiumSponge
version: '${project.version}'
main: com.github.unldenis.premiumsponge.PremiumSponge
softdepend: [ WorldGuard ]
authors: [ unldenis ]
commands:
  removesponges:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
